import { useMemo, useState } from "react";
import { useAdminData } from "../../context/useAdminData";

export default function Responders() {
  const { responderData, incidentData } = useAdminData();
  const [filter, setFilter] = useState("ALL");
  const [query, setQuery] = useState("");
  const visible = useMemo(() => responderData.filter((responder) => (filter === "ALL" || responder.status === filter) && `${responder.name} ${responder.type}`.toLowerCase().includes(query.toLowerCase())), [filter, query, responderData]);
  return <main className="dashboard management-page"><div className="page-heading"><div><p className="eyebrow">OPERATIONS / RESPONSE TEAMS</p><h1>Responders</h1><p className="subtitle">Monitor team availability and current campus assignments.</p></div><span className="queue-count">{responderData.length} teams</span></div><section className="management-stats"><Stat label="Available" value={responderData.filter((item) => item.status === "AVAILABLE").length} /><Stat label="Busy" value={responderData.filter((item) => item.status === "BUSY").length} /><Stat label="Offline" value={responderData.filter((item) => item.status === "OFFLINE").length} /><Stat label="Online" value={responderData.filter((item) => item.status !== "OFFLINE").length} /></section><section className="management-card"><div className="management-toolbar"><label className="search-box"><span>Search responders</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Team or type" /></label><div className="filter-row report-filters">{["ALL", "AVAILABLE", "BUSY", "OFFLINE"].map((item) => <button key={item} className={filter === item ? "filter active" : "filter"} onClick={() => setFilter(item)}>{item}</button>)}</div></div><div className="responder-list">{visible.map((responder) => { const assignment = incidentData.find((incident) => incident.assignedResponder === responder.name); return <div className="responder-row" key={responder.id}><span className="responder-avatar">{responder.name.charAt(0)}</span><span><strong>{responder.name}</strong><small>{responder.type}</small></span><span className={`availability ${responder.status.toLowerCase()}`}>{responder.status}</span><span>{assignment ? assignment.id : "No active assignment"}</span><span>{responder.availability}</span></div>; })}</div></section></main>;
}
function Stat({ label, value }) { return <div className="stat-card"><div><p>{label}</p><h2>{value}</h2></div></div>; }
